use_frameworks!

target 'iOS App' do
  platform :ios, '15.0'
  pod 'shared', :path => './shared'
  pod 'KMPNativeCoroutinesCore', :path => '../'
  pod 'KMPNativeCoroutinesCombine', :path => '../'
  pod 'KMPNativeCoroutinesRxSwift', :path => '../'
  pod 'KMPNativeCoroutinesAsync', :path => '../'
end

target 'iOS Tests' do
  platform :ios, '15.0'
  pod 'shared', :path => './shared'
  pod 'KMPNativeCoroutinesCore', :path => '../'
  pod 'KMPNativeCoroutinesCombine', :path => '../'
  pod 'KMPNativeCoroutinesRxSwift', :path => '../'
  pod 'KMPNativeCoroutinesAsync', :path => '../'
end

target 'macOS App' do
  platform :osx, '12.0'
  pod 'shared', :path => './shared'
  pod 'KMPNativeCoroutinesCore', :path => '../'
  pod 'KMPNativeCoroutinesCombine', :path => '../'
  pod 'KMPNativeCoroutinesRxSwift', :path => '../'
  pod 'KMPNativeCoroutinesAsync', :path => '../'
end

target 'macOS Tests' do
  platform :osx, '12.0'
  pod 'shared', :path => './shared'
  pod 'KMPNativeCoroutinesCore', :path => '../'
  pod 'KMPNativeCoroutinesCombine', :path => '../'
  pod 'KMPNativeCoroutinesRxSwift', :path => '../'
  pod 'KMPNativeCoroutinesAsync', :path => '../'
end

target 'tvOS App' do
  platform :tvos, '15.0'
  pod 'shared', :path => './shared'
  pod 'KMPNativeCoroutinesCore', :path => '../'
  pod 'KMPNativeCoroutinesCombine', :path => '../'
  pod 'KMPNativeCoroutinesRxSwift', :path => '../'
end

target 'tvOS Tests' do
  platform :tvos, '15.0'
  pod 'shared', :path => './shared'
  pod 'KMPNativeCoroutinesCore', :path => '../'
  pod 'KMPNativeCoroutinesCombine', :path => '../'
  pod 'KMPNativeCoroutinesRxSwift', :path => '../'
end

target 'watchOS App WatchKit Extension' do
  platform :watchos, '8.0'
  pod 'shared', :path => './shared'
  pod 'KMPNativeCoroutinesCore', :path => '../'
  pod 'KMPNativeCoroutinesCombine', :path => '../'
  pod 'KMPNativeCoroutinesRxSwift', :path => '../'
end

target 'watchOS Tests' do
  platform :watchos, '8.0'
  pod 'shared', :path => './shared'
  pod 'KMPNativeCoroutinesCore', :path => '../'
  pod 'KMPNativeCoroutinesCombine', :path => '../'
  pod 'KMPNativeCoroutinesRxSwift', :path => '../'
end
